-- MySQL Script generated by MySQL Workbench
-- Sat Aug 12 18:34:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `idroles` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idroles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EDUCATIONAL_SITUATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EDUCATIONAL_SITUATION` (
  `idEDUCATIONAL_SITUATION` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idEDUCATIONAL_SITUATION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WORK_PROFILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WORK_PROFILE` (
  `wp_id` INT NOT NULL,
  `gender` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `education_status` VARCHAR(45) NULL,
  `english_level` VARCHAR(45) NULL,
  `cv_url` VARCHAR(45) NULL,
  `linkedin_url` VARCHAR(45) NULL,
  `github_url` VARCHAR(45) NULL,
  `featured_project` VARCHAR(45) NULL,
  `work_avaliability` VARCHAR(45) NULL,
  `dev_experience` VARCHAR(45) NULL,
  `educational_level` VARCHAR(45) NULL,
  `comment` VARCHAR(45) NULL,
  `ideal_work_comment` VARCHAR(45) NULL,
  `relocation_option` VARCHAR(45) NULL,
  `visa` VARCHAR(45) NULL,
  `design` VARCHAR(45) NULL,
  `cv_file` VARCHAR(45) NULL,
  `EDUCATIONAL_SITUATION_idEDUCATIONAL_SITUATION` INT NOT NULL,
  `roles_idroles` INT NOT NULL,
  PRIMARY KEY (`wp_id`),
  INDEX `fk_WORK_PROFILE_roles1_idx` (`roles_idroles` ASC) VISIBLE,
  INDEX `fk_EDUCATION_SITUACION_idx` (`EDUCATIONAL_SITUATION_idEDUCATIONAL_SITUATION` ASC) VISIBLE,
  CONSTRAINT `fk_WORK_PROFILE_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `mydb`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EDUCATION_SITUACION`
    FOREIGN KEY (`EDUCATIONAL_SITUATION_idEDUCATIONAL_SITUATION`)
    REFERENCES `mydb`.`EDUCATIONAL_SITUATION` (`idEDUCATIONAL_SITUATION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '					';


-- -----------------------------------------------------
-- Table `mydb`.`user_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_statuses` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `idUSER` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `user_statuses_id` INT NOT NULL,
  `WORK_PROFILE_wp_id` INT NOT NULL,
  PRIMARY KEY (`idUSER`, `user_statuses_id`),
  INDEX `fk_USER_user_statuses1_idx` (`user_statuses_id` ASC) VISIBLE,
  INDEX `fk_USER_WORK_PROFILE1_idx` (`WORK_PROFILE_wp_id` ASC) VISIBLE,
  CONSTRAINT `fk_USER_user_statuses1`
    FOREIGN KEY (`user_statuses_id`)
    REFERENCES `mydb`.`user_statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_WORK_PROFILE1`
    FOREIGN KEY (`WORK_PROFILE_wp_id`)
    REFERENCES `mydb`.`WORK_PROFILE` (`wp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EDUCATION_EXPERIENCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EDUCATION_EXPERIENCE` (
  `id` INT NOT NULL,
  `institute_name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `area` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `graduation_year` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EDUCATION_EXPERIENCE_has_WORK_PROFILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EDUCATION_EXPERIENCE_has_WORK_PROFILE` (
  `EDUCATION_EXPERIENCE_id` INT NOT NULL,
  `WORK_PROFILE_wp_id` INT NOT NULL,
  PRIMARY KEY (`EDUCATION_EXPERIENCE_id`, `WORK_PROFILE_wp_id`),
  INDEX `fk_EDUCATION_EXPERIENCE_has_WORK_PROFILE_WORK_PROFILE1_idx` (`WORK_PROFILE_wp_id` ASC) VISIBLE,
  INDEX `fk_EDUCATION_EXPERIENCE_has_WORK_PROFILE_EDUCATION_EXPERIEN_idx` (`EDUCATION_EXPERIENCE_id` ASC) VISIBLE,
  CONSTRAINT `fk_EDUCATION_EXPERIENCE_has_WORK_PROFILE_EDUCATION_EXPERIENCE1`
    FOREIGN KEY (`EDUCATION_EXPERIENCE_id`)
    REFERENCES `mydb`.`EDUCATION_EXPERIENCE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EDUCATION_EXPERIENCE_has_WORK_PROFILE_WORK_PROFILE1`
    FOREIGN KEY (`WORK_PROFILE_wp_id`)
    REFERENCES `mydb`.`WORK_PROFILE` (`wp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LANGUAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LANGUAGE` (
  `idLANGUAGE` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idLANGUAGE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LANGUAGE_has_WORK_PROFILE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LANGUAGE_has_WORK_PROFILE` (
  `LANGUAGE_idLANGUAGE` INT NOT NULL,
  `WORK_PROFILE_wp_id` INT NOT NULL,
  PRIMARY KEY (`LANGUAGE_idLANGUAGE`, `WORK_PROFILE_wp_id`),
  INDEX `fk_LANGUAGE_has_WORK_PROFILE_WORK_PROFILE1_idx` (`WORK_PROFILE_wp_id` ASC) VISIBLE,
  INDEX `fk_LANGUAGE_has_WORK_PROFILE_LANGUAGE1_idx` (`LANGUAGE_idLANGUAGE` ASC) VISIBLE,
  CONSTRAINT `fk_LANGUAGE_has_WORK_PROFILE_LANGUAGE1`
    FOREIGN KEY (`LANGUAGE_idLANGUAGE`)
    REFERENCES `mydb`.`LANGUAGE` (`idLANGUAGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LANGUAGE_has_WORK_PROFILE_WORK_PROFILE1`
    FOREIGN KEY (`WORK_PROFILE_wp_id`)
    REFERENCES `mydb`.`WORK_PROFILE` (`wp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FRAMEWORK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FRAMEWORK` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tools` (
  `idtools` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idtools`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`soft_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`soft_skills` (
  `idsoft` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idsoft`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles_has_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles_has_USER` (
  `roles_idroles` INT NOT NULL,
  `USER_idUSER` INT NOT NULL,
  `USER_user_statuses_id` INT NOT NULL,
  PRIMARY KEY (`roles_idroles`, `USER_idUSER`, `USER_user_statuses_id`),
  INDEX `fk_roles_has_USER_USER1_idx` (`USER_idUSER` ASC, `USER_user_statuses_id` ASC) VISIBLE,
  INDEX `fk_roles_has_USER_roles1_idx` (`roles_idroles` ASC) VISIBLE,
  CONSTRAINT `fk_roles_has_USER_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `mydb`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_has_USER_USER1`
    FOREIGN KEY (`USER_idUSER` , `USER_user_statuses_id`)
    REFERENCES `mydb`.`USER` (`idUSER` , `user_statuses_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recruiter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recruiter` (
  `idrecruiter` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `company` VARCHAR(45) NULL,
  `charge` VARCHAR(45) NULL,
  `question` VARCHAR(45) NULL,
  PRIMARY KEY (`idrecruiter`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CAREER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CAREER` (
  `idCAREER` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `EDUCATION_EXPERIENCE_has_WORK_PROFILE_EDUCATION_EXPERIENCE_id` INT NOT NULL,
  `EDUCATION_EXPERIENCE_has_WORK_PROFILE_WORK_PROFILE_wp_id` INT NOT NULL,
  PRIMARY KEY (`idCAREER`),
  INDEX `fk_CAREER_EDUCATION_EXPERIENCE_has_WORK_PROFILE1_idx` (`EDUCATION_EXPERIENCE_has_WORK_PROFILE_EDUCATION_EXPERIENCE_id` ASC, `EDUCATION_EXPERIENCE_has_WORK_PROFILE_WORK_PROFILE_wp_id` ASC) VISIBLE,
  CONSTRAINT `fk_CAREER_EDUCATION_EXPERIENCE_has_WORK_PROFILE1`
    FOREIGN KEY (`EDUCATION_EXPERIENCE_has_WORK_PROFILE_EDUCATION_EXPERIENCE_id` , `EDUCATION_EXPERIENCE_has_WORK_PROFILE_WORK_PROFILE_wp_id`)
    REFERENCES `mydb`.`EDUCATION_EXPERIENCE_has_WORK_PROFILE` (`EDUCATION_EXPERIENCE_id` , `WORK_PROFILE_wp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INSTITUTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSTITUTION` (
  `idinstitution` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `CAREER_idCAREER` INT NOT NULL,
  PRIMARY KEY (`idinstitution`),
  INDEX `fk_intitution_CAREER1_idx` (`CAREER_idCAREER` ASC) VISIBLE,
  CONSTRAINT `fk_intitution_CAREER1`
    FOREIGN KEY (`CAREER_idCAREER`)
    REFERENCES `mydb`.`CAREER` (`idCAREER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KNOWLEDGE_LEVEL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KNOWLEDGE_LEVEL` (
  `idKNOWLEDGE_LEVEL` INT NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(45) NULL,
  `WORK_PROFILE_wp_id` INT NOT NULL,
  PRIMARY KEY (`idKNOWLEDGE_LEVEL`),
  INDEX `fk_KNOWLEDGE_LEVEL_WORK_PROFILE1_idx` (`WORK_PROFILE_wp_id` ASC) VISIBLE,
  CONSTRAINT `fk_KNOWLEDGE_LEVEL_WORK_PROFILE1`
    FOREIGN KEY (`WORK_PROFILE_wp_id`)
    REFERENCES `mydb`.`WORK_PROFILE` (`wp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recruiter_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recruiter_has_roles` (
  `recruiter_idrecruiter` INT NOT NULL,
  `roles_idroles` INT NOT NULL,
  PRIMARY KEY (`recruiter_idrecruiter`, `roles_idroles`),
  INDEX `fk_recruiter_has_roles_roles1_idx` (`roles_idroles` ASC) VISIBLE,
  INDEX `fk_recruiter_has_roles_recruiter1_idx` (`recruiter_idrecruiter` ASC) VISIBLE,
  CONSTRAINT `fk_recruiter_has_roles_recruiter1`
    FOREIGN KEY (`recruiter_idrecruiter`)
    REFERENCES `mydb`.`recruiter` (`idrecruiter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recruiter_has_roles_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `mydb`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WORK_PROFILE_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WORK_PROFILE_has_roles` (
  `WORK_PROFILE_wp_id` INT NOT NULL,
  `roles_idroles` INT NOT NULL,
  PRIMARY KEY (`WORK_PROFILE_wp_id`, `roles_idroles`),
  INDEX `fk_WORK_PROFILE_has_roles_roles1_idx` (`roles_idroles` ASC) VISIBLE,
  INDEX `fk_WORK_PROFILE_has_roles_WORK_PROFILE1_idx` (`WORK_PROFILE_wp_id` ASC) VISIBLE,
  CONSTRAINT `fk_WORK_PROFILE_has_roles_WORK_PROFILE1`
    FOREIGN KEY (`WORK_PROFILE_wp_id`)
    REFERENCES `mydb`.`WORK_PROFILE` (`wp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WORK_PROFILE_has_roles_roles1`
    FOREIGN KEY (`roles_idroles`)
    REFERENCES `mydb`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KNOWLEDGE_LEVEL_has_soft_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KNOWLEDGE_LEVEL_has_soft_skills` (
  `KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL` INT NOT NULL,
  `soft_skills_idsoft` INT NOT NULL,
  PRIMARY KEY (`KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL`, `soft_skills_idsoft`),
  INDEX `fk_KNOWLEDGE_LEVEL_has_soft_skills_soft_skills1_idx` (`soft_skills_idsoft` ASC) VISIBLE,
  INDEX `fk_KNOWLEDGE_LEVEL_has_soft_skills_KNOWLEDGE_LEVEL1_idx` (`KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL` ASC) VISIBLE,
  CONSTRAINT `fk_KNOWLEDGE_LEVEL_has_soft_skills_KNOWLEDGE_LEVEL1`
    FOREIGN KEY (`KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL`)
    REFERENCES `mydb`.`KNOWLEDGE_LEVEL` (`idKNOWLEDGE_LEVEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KNOWLEDGE_LEVEL_has_soft_skills_soft_skills1`
    FOREIGN KEY (`soft_skills_idsoft`)
    REFERENCES `mydb`.`soft_skills` (`idsoft`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KNOWLEDGE_LEVEL_has_tools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KNOWLEDGE_LEVEL_has_tools` (
  `KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL` INT NOT NULL,
  `tools_idtools` INT NOT NULL,
  PRIMARY KEY (`KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL`, `tools_idtools`),
  INDEX `fk_KNOWLEDGE_LEVEL_has_tools_tools1_idx` (`tools_idtools` ASC) VISIBLE,
  INDEX `fk_KNOWLEDGE_LEVEL_has_tools_KNOWLEDGE_LEVEL1_idx` (`KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL` ASC) VISIBLE,
  CONSTRAINT `fk_KNOWLEDGE_LEVEL_has_tools_KNOWLEDGE_LEVEL1`
    FOREIGN KEY (`KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL`)
    REFERENCES `mydb`.`KNOWLEDGE_LEVEL` (`idKNOWLEDGE_LEVEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KNOWLEDGE_LEVEL_has_tools_tools1`
    FOREIGN KEY (`tools_idtools`)
    REFERENCES `mydb`.`tools` (`idtools`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KNOWLEDGE_LEVEL_has_FRAMEWORK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KNOWLEDGE_LEVEL_has_FRAMEWORK` (
  `KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL` INT NOT NULL,
  `FRAMEWORK_ID` INT NOT NULL,
  PRIMARY KEY (`KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL`, `FRAMEWORK_ID`),
  INDEX `fk_KNOWLEDGE_LEVEL_has_FRAMEWORK_FRAMEWORK1_idx` (`FRAMEWORK_ID` ASC) VISIBLE,
  INDEX `fk_KNOWLEDGE_LEVEL_has_FRAMEWORK_KNOWLEDGE_LEVEL1_idx` (`KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL` ASC) VISIBLE,
  CONSTRAINT `fk_KNOWLEDGE_LEVEL_has_FRAMEWORK_KNOWLEDGE_LEVEL1`
    FOREIGN KEY (`KNOWLEDGE_LEVEL_idKNOWLEDGE_LEVEL`)
    REFERENCES `mydb`.`KNOWLEDGE_LEVEL` (`idKNOWLEDGE_LEVEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KNOWLEDGE_LEVEL_has_FRAMEWORK_FRAMEWORK1`
    FOREIGN KEY (`FRAMEWORK_ID`)
    REFERENCES `mydb`.`FRAMEWORK` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
